version: '3.5'

services:
  netswatchgo:
    build:
      context: ./
      dockerfile: Dockerfile
    image: docker.cetcxl.local/netswatch:1.0.5-2-g56ba67e5
    environment:
      - NW_ETCD_ENDPOINTS=http://localhost:2379
      - NW_ETCD_USERNAME=username
      - NW_ETCD_PASSWORD=password
      - NW_SUBNET_FILE=/run/flannel/sn.env
      - NW_PUBLIC_IP=172.16.66.6
      - NW_IFACE=172.16.66.6
      - NW_DNS_ENDPOINTS=http://consul.cetcxl.com:8500
      - NW_DNS_TOKEN=abcdefgh-1234-abcd-1234-abcdefghijkl
      - NW_NETWORK_NAME=nwnet
      - NW_ORG_NAME=banana
      - NW_NODE_TYPE=router
      - NW_NETDATA_PORT=19999
      - NW_NETDATA_ENABLED=false
      - NW_LOG_LEVEL=debug
      - GODEBUG=netdns=go
    volumes:
      - /run/flannel:/run/flannel:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
      - NET_ADMIN
    network_mode: "host"
    tty: true
    restart: always
